from __future__ import annotations

from typing import Any


ONTOLOGY: dict[str, Any] = {
    "version": "0.2.0",
    "part_families": {
        "impeller": {
            "base_features": [
                "hub",
                "blade",
                "blade_root",
                "blade_airfoil",
                "inlet",
                "outlet",
                "flow_path",
                "optional_shroud",
                "mounting_interface",
                "passage",
            ],
            "facet_axes": {
                "flow_topology": ["axial", "mixed", "radial"],
                "shroud_topology": ["open", "semi_open", "closed"],
                "suction_topology": ["single_suction", "double_suction"],
                "blade_exit_geometry": ["backward_curved", "radial", "forward_curved"],
                "working_domain": [
                    "pump",
                    "compressor",
                    "fan_or_blower",
                    "turbine_or_runner",
                    "unknown",
                ],
                "passage_topology": [
                    "throughflow_bladed_channel",
                    "single_channel",
                    "multi_channel",
                    "recessed_vortex",
                    "cutter",
                ],
            },
        }
    },
    "terms": [
        "hub",
        "disk",
        "blade_root",
        "blade_airfoil",
        "impeller",
        "inducer",
        "inner_ring",
        "outer_ring",
        "vane",
        "flow_path",
        "mounting_interface",
        "passage",
        "recessed_vortex",
        "free_passage_cavity",
    ],
    "relations": [
        "attached_to",
        "embedded_contact",
        "bridges",
        "contains",
        "intersects",
        "clearance_to",
        "bounds_flow_path",
        "patterned_around_axis",
    ],
}


IMPELLER_FACET_AXES: dict[str, list[str]] = ONTOLOGY["part_families"]["impeller"]["facet_axes"]


IMPELLER_PRESETS: dict[str, dict[str, Any]] = {
    "axisymmetric_nurbs_open_throughflow_study": {
        "name": "Axisymmetric NURBS open throughflow study",
        "summary": "Open radial throughflow impeller with revolved NURBS hub/tip profiles and conformal pressure/suction blade surfaces.",
        "facets": {
            "flow_topology": "radial",
            "shroud_topology": "open",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "backward_curved",
            "working_domain": "pump",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 7,
            "inlet_radius_mm": 180.0,
            "exit_radius_mm": 620.0,
            "inlet_blade_height_mm": 150.0,
            "outlet_blade_height_mm": 72.0,
            "inlet_blade_angle_deg": 21.0,
            "outlet_blade_angle_deg": 42.0,
            "blade_thickness_mm": 18.0,
            "blade_curve_gain": 1.0,
            "hub_curve_height_mm": 82.0,
            "mounting_bore_radius_mm": 40.0,
            "blade_wrap_deg": 118.0,
            "blade_lean_deg": 8.0,
        },
        "source_refs": [
            "cfturbo_impeller_design_steps",
            "cfturbo_meridional_contour",
            "cfturbo_beta_blade_angle_progression",
            "research_inferred_nurbs_control_points",
        ],
    },
    "axisymmetric_nurbs_closed_throughflow_study": {
        "name": "Axisymmetric NURBS closed throughflow study",
        "summary": "Closed radial throughflow impeller with revolved NURBS hub/shroud profiles and conformal pressure/suction blade surfaces.",
        "facets": {
            "flow_topology": "radial",
            "shroud_topology": "closed",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "backward_curved",
            "working_domain": "pump",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 6,
            "inlet_radius_mm": 190.0,
            "exit_radius_mm": 600.0,
            "inlet_blade_height_mm": 130.0,
            "outlet_blade_height_mm": 68.0,
            "inlet_blade_angle_deg": 22.0,
            "outlet_blade_angle_deg": 38.0,
            "blade_thickness_mm": 16.0,
            "blade_curve_gain": 1.0,
            "hub_curve_height_mm": 74.0,
            "mounting_bore_radius_mm": 42.0,
            "blade_wrap_deg": 95.0,
            "blade_lean_deg": -5.0,
        },
        "source_refs": [
            "cfturbo_impeller_design_steps",
            "cfturbo_meridional_contour",
            "cfturbo_beta_blade_angle_progression",
            "research_inferred_nurbs_control_points",
        ],
    },
    "radial_open_backward_single_reference": {
        "name": "Radial open backward single reference",
        "summary": "UPCommons-derived radial pump baseline with exposed blade tips.",
        "facets": {
            "flow_topology": "radial",
            "shroud_topology": "open",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "backward_curved",
            "working_domain": "pump",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 7,
            "inlet_radius_mm": 420.2,
            "exit_radius_mm": 1400.65,
            "inlet_blade_height_mm": 394.0,
            "outlet_blade_height_mm": 251.0,
            "inlet_blade_angle_deg": 17.47,
            "outlet_blade_angle_deg": 21.19,
            "blade_thickness_mm": 56.0,
            "blade_curve_gain": 1.0,
            "hub_curve_height_mm": 0.0,
        },
        "source_refs": [
            "upcommons_centrifugal_pump_impeller",
            "ksb_impeller_lexicon",
            "cfturbo_impeller_design_steps",
        ],
    },
    "mixed_semi_open_radial_double_study": {
        "name": "Mixed semi-open radial double-suction study",
        "summary": "Mixed-flow study with one shroud side and mirrored inlet construction.",
        "facets": {
            "flow_topology": "mixed",
            "shroud_topology": "semi_open",
            "suction_topology": "double_suction",
            "blade_exit_geometry": "radial",
            "working_domain": "compressor",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 10,
            "inlet_radius_mm": 360.0,
            "exit_radius_mm": 1060.0,
            "inlet_blade_height_mm": 420.0,
            "outlet_blade_height_mm": 310.0,
            "inlet_blade_angle_deg": 22.0,
            "outlet_blade_angle_deg": 30.0,
            "blade_thickness_mm": 42.0,
            "blade_curve_gain": 1.55,
            "hub_curve_height_mm": 260.0,
        },
        "source_refs": ["research_proxy", "hydraulic_institute_rotodynamic_context"],
    },
    "axial_closed_forward_single_study": {
        "name": "Axial closed forward single-suction study",
        "summary": "Axial-flow study with closed shroud parameter lines and forward-curved blades.",
        "facets": {
            "flow_topology": "axial",
            "shroud_topology": "closed",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "forward_curved",
            "working_domain": "fan_or_blower",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 12,
            "inlet_radius_mm": 460.0,
            "exit_radius_mm": 690.0,
            "inlet_blade_height_mm": 360.0,
            "outlet_blade_height_mm": 340.0,
            "inlet_blade_angle_deg": 34.0,
            "outlet_blade_angle_deg": 58.0,
            "blade_thickness_mm": 34.0,
            "blade_curve_gain": 1.2,
            "hub_curve_height_mm": 300.0,
        },
        "source_refs": ["research_proxy", "grundfos_main_impeller_types"],
    },
    "radial_open_recessed_vortex_study": {
        "name": "Radial open recessed vortex study",
        "summary": "Free-flow/vortex wastewater-style impeller with recessed blades and a large passage cavity.",
        "facets": {
            "flow_topology": "radial",
            "shroud_topology": "open",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "forward_curved",
            "working_domain": "pump",
            "passage_topology": "recessed_vortex",
        },
        "parameters": {
            "blade_count": 8,
            "inlet_radius_mm": 260.0,
            "exit_radius_mm": 900.0,
            "inlet_blade_height_mm": 180.0,
            "outlet_blade_height_mm": 130.0,
            "inlet_blade_angle_deg": 18.0,
            "outlet_blade_angle_deg": 70.0,
            "blade_thickness_mm": 42.0,
            "blade_curve_gain": 1.7,
            "hub_curve_height_mm": 120.0,
        },
        "source_refs": ["ksb_free_flow_impeller", "ksb_wastewater_impellers", "grundfos_vortex_impeller"],
    },
    "twisted_open_impeller_study": {
        "name": "Twisted open impeller conformance study",
        "summary": "Open impeller with warped hub/tip fields; blade hub and tip boundaries are constructed from those surfaces.",
        "facets": {
            "flow_topology": "mixed",
            "shroud_topology": "open",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "backward_curved",
            "working_domain": "pump",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 9,
            "inlet_radius_mm": 300.0,
            "exit_radius_mm": 1150.0,
            "inlet_blade_height_mm": 320.0,
            "outlet_blade_height_mm": 210.0,
            "inlet_blade_angle_deg": 19.0,
            "outlet_blade_angle_deg": 64.0,
            "blade_thickness_mm": 42.0,
            "blade_curve_gain": 2.3,
            "hub_curve_height_mm": 280.0,
            "hub_twist_deg": 32.0,
            "tip_twist_deg": 58.0,
            "hub_warp_mm": 42.0,
            "tip_warp_mm": 88.0,
        },
        "source_refs": ["reference_image_open_twisted_impeller", "research_proxy"],
    },
    "twisted_closed_impeller_study": {
        "name": "Twisted closed impeller conformance study",
        "summary": "Closed impeller with warped hub/shroud fields; blade tip boundaries conform to the shroud surface.",
        "facets": {
            "flow_topology": "mixed",
            "shroud_topology": "closed",
            "suction_topology": "single_suction",
            "blade_exit_geometry": "backward_curved",
            "working_domain": "pump",
            "passage_topology": "throughflow_bladed_channel",
        },
        "parameters": {
            "blade_count": 8,
            "inlet_radius_mm": 340.0,
            "exit_radius_mm": 1180.0,
            "inlet_blade_height_mm": 300.0,
            "outlet_blade_height_mm": 230.0,
            "inlet_blade_angle_deg": 22.0,
            "outlet_blade_angle_deg": 50.0,
            "blade_thickness_mm": 38.0,
            "blade_curve_gain": 2.0,
            "hub_curve_height_mm": 240.0,
            "hub_twist_deg": 24.0,
            "tip_twist_deg": 46.0,
            "hub_warp_mm": 36.0,
            "tip_warp_mm": 70.0,
        },
        "source_refs": ["reference_image_closed_twisted_impeller", "research_proxy"],
    },
}


LEGACY_CENTRIFUGAL_IMPELLER_FACETS = {
    "flow_topology": "radial",
    "shroud_topology": "open",
    "suction_topology": "single_suction",
    "blade_exit_geometry": "backward_curved",
    "working_domain": "pump",
    "passage_topology": "throughflow_bladed_channel",
}
